version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - HASHED_PASSWORD= # password hash
      - SUDO_PASSWORD_HASH= # password hash
      - PROXY_DOMAIN= # domain name
      - DEFAULT_WORKSPACE=/config/project
    volumes:
      - /root/code:/config
    ports:
      - 8443:8443
    restart: unless-stopped
