version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /path/to/pocketbase/data:/pb_data
      - /path/to/pocketbase/public:/pb_public # optional
