version: "3"
services:
  portainer:
    image: "portainer/portainer-ce:latest"
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
